### ISSUE TITLE
Any app Crashes or cause respring

### ISSUE THREAD

**Issue by jj19** [PoomSmart/EmojiPort-Legacy#4] opened 2015-04-27 11:28 UTC
Keyboard crashes application when switching to Emojis. Or causes respring on home screen. Emoji83 ver. 1.0-24 + EmojiLayout ver 1.0-7.

**Comment by jj19** [comment] 2015-04-27 11:29
iPhone 6

**Comment by PoomSmart** [comment] 2015-04-27 11:53
Send me crash log.
However, this is an issue caused by EmojiLayout. So I will close this issue for Emoji83.

**Closed as completed by PoomSmart** 2015-04-27 11:53 UTC
